// @ts-check

import js from "@eslint/js"
import globals from "globals"
import { defineConfig } from "eslint/config"
import tseslint from "typescript-eslint"

export default defineConfig(
  {
    // `components` is generated by scripts/build.mjs and holds the minified bundle; linting it would
    // report findings about output no one edits.
    ignores: ["node_modules/**", "dist/**", "public/**", "components/**", "src/.observablehq/**"],
  },
  {
    // The app is one TypeScript module graph running in the browser. Type-checked rules rather than
    // the syntactic set: the defects this migration was for - a union read without narrowing, a value
    // that could be null - are only visible to a linter that has the types.
    files: ["src/**/*.ts"],
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      globals: globals.browser,
      parserOptions: {
        // Both projects: src/lib/markdown-fences.test.ts reads the markdown pages off disk and so
        // belongs to tsconfig.node.json. Without naming it here the project service cannot find the
        // file, and ESLint reports nothing about it at all.
        project: ["./tsconfig.json", "./tsconfig.node.json"],
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Framework hardcodes `verbatimModuleSyntax` in its esbuild options, so a type imported as a
      // value becomes an import of a module that does not exist at runtime. This rule is what keeps
      // that from being written by hand.
      "@typescript-eslint/consistent-type-imports": "error",
    },
  },
  {
    // Two rules that are right about production code and wrong about a suite. Everything else stays
    // on: the type-checked rules found real defects in these files during the conversion, and a test
    // asserting on the wrong shape is exactly the mistake worth catching.
    files: ["src/lib/**/*.test.ts"],
    rules: {
      // A stub standing in for `fetchText` has to return a promise, and `async () => text` is the
      // plainest way to write one. There is nothing for it to await.
      "@typescript-eslint/require-await": "off",
      // Saving `window.getSelection` to restore it afterwards is the point, not an accident: the test
      // never calls the saved reference, it puts it back.
      "@typescript-eslint/unbound-method": "off",
      // Vitest types its asymmetric matchers (`expect.stringContaining` and friends) as `any`, so
      // every use of one inside a toMatchObject reads as an unchecked assignment. That is the
      // library's typing, not something a test can state better.
      "@typescript-eslint/no-unsafe-assignment": "off",
    },
  },
  {
    // The build scripts stay JavaScript, matching tapoo: they run directly under node, and compiling
    // them would put a build step in front of the script that does the building.
    files: ["scripts/**/*.mjs", "*.config.mjs", "observablehq.config.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      globals: globals.node,
    },
  },
)
